// Build (query, memory) candidate pairs for the sati-recall gate.
//
//   node gen_sati_pairs.mjs --pool <pool dir> [--model deepseek-v4-flash:cloud]
//        [--url http://127.0.0.1:11434/v1] [--batch 8] [--concurrency 4]
//
// A generator model (NOT one of the annotators) writes, per source memory A,
// one question A answers and one same-topic question A does not answer.
// Pairs per A: (answerable, A), (near_miss, A), (answerable, B) with B the
// TF-IDF nearest other memory in the same split. Real operator questions from
// Steve's volume are paired with their TF-IDF nearest memory. The generator's
// intent is recorded as `construction` only; labels come from annotate.mjs.
import fs from 'node:fs';
import path from 'node:path';
import { args, readJsonl, writeJsonl, chat, firstJson, pool, splitOf, tfidfIndex, sha256File } from './common.mjs';

const a = args();
if (!a.pool) throw new Error('--pool required');
const url = a.url || 'http://127.0.0.1:11434/v1';
const model = a.model || 'deepseek-v4-flash:cloud';
const batch = Number(a.batch || 8);
const promptPath = new URL('../../prompts/gen_sati_queries.txt', import.meta.url);
const template = fs.readFileSync(promptPath, 'utf8');

const sources = readJsonl(path.join(a.pool, 'sati_sources.jsonl'));
const cachePath = path.join(a.pool, `sati_queries.${model.replace(/[^a-z0-9.-]/gi, '_')}.jsonl`);
const cache = new Map(readJsonl(cachePath).map((r) => [r.id, r]));
const todo = sources.filter((s) => !cache.has(s.id));
const batches = [];
for (let i = 0; i < todo.length; i += batch) batches.push(todo.slice(i, i + batch));
console.error(`sources ${sources.length}, cached ${cache.size}, batches ${batches.length}`);

await pool(batches, Number(a.concurrency || 4), async (b, bi) => {
  const items = b.map((s, i) => `[m${i + 1}] ${s.text}`).join('\n\n');
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const r = await chat({ url, model, prompt: template.replace('{items}', items) });
      const qs = firstJson(r.text)?.queries;
      if (!Array.isArray(qs)) throw new Error('no queries array');
      for (const q of qs) {
        const k = Number(String(q.id).replace(/\D/g, '')) - 1;
        if (b[k] && q.answerable && q.near_miss) {
          const row = { id: b[k].id, answerable: String(q.answerable), near_miss: String(q.near_miss), model: r.model };
          cache.set(row.id, row);
          fs.appendFileSync(cachePath, JSON.stringify(row) + '\n');
        }
      }
      console.error(`batch ${bi} ok`);
      return;
    } catch (e) {
      console.error(`batch ${bi} attempt ${attempt}: ${e.message}`);
    }
  }
});

// Pairs.
const bySplit = {};
for (const s of sources) (bySplit[splitOf(s.group)] ||= []).push(s);
const idx = Object.fromEntries(Object.entries(bySplit).map(([k, v]) => [k, tfidfIndex(v.map((s) => s.text))]));
const pairs = [];
const pairOf = (id, query, mem, group, construction, qsource) => ({
  id, query, memory: mem.text, memory_id: mem.id, group, construction,
  source: `${qsource}; memory ${mem.source}`,
});
for (const s of sources) {
  const q = cache.get(s.id);
  if (!q) continue;
  const split = splitOf(s.group);
  pairs.push(pairOf(`sr:${s.id}:ans`, q.answerable, s, s.group, 'generated-answerable', `query generated by ${q.model}`));
  pairs.push(pairOf(`sr:${s.id}:near`, q.near_miss, s, s.group, 'generated-near-miss', `query generated by ${q.model}`));
  const nn = idx[split].query(s.text).map(([i]) => bySplit[split][i]).find((m) => m.id !== s.id && m.group !== s.group);
  if (nn) pairs.push(pairOf(`sr:${s.id}:nn`, q.answerable, nn, s.group, 'generated-answerable-vs-nearest-other', `query generated by ${q.model} for ${s.id}`));
}
const all = tfidfIndex(sources.map((s) => s.text));
for (const rq of readJsonl(path.join(a.pool, 'real_queries.jsonl'))) {
  const [i] = all.query(rq.query)[0];
  pairs.push(pairOf(`sr:${rq.id}:real`, rq.query, sources[i], rq.group, 'real-operator-question-vs-nearest', rq.source));
}
writeJsonl(path.join(a.pool, 'sati_recall.pool.jsonl'), pairs);
console.log(JSON.stringify({ pairs: pairs.length, generator: model, prompt_sha256: sha256File(promptPath) }));
